/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8 */

#ifndef PB_ICHNAEA_ICHNAEA_PB_H_INCLUDED
#define PB_ICHNAEA_ICHNAEA_PB_H_INCLUDED
#include <pb.h>
#include "mbed_rpc.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* System services that are available to all nodes in the network. */
typedef enum _ichnaea_Service {
    ichnaea_Service_SVC_IDENTITY = 0
} ichnaea_Service;

/* Message types available */
typedef enum _ichnaea_Message {
    ichnaea_Message_MSG_GET_ID_REQ = 0,
    ichnaea_Message_MSG_GET_ID_RSP = 1
} ichnaea_Message;

/* Version of the message. This is used to ensure that the message is compatible with the receiver. */
typedef enum _ichnaea_MessageVersion {
    ichnaea_MessageVersion_MSG_VER_GET_ID_REQ = 0,
    ichnaea_MessageVersion_MSG_VER_GET_ID_RSP = 0
} ichnaea_MessageVersion;

/* Struct definitions */
/* This is a broadcasted message to all nodes in the network to respond with their unique identifier.
 This allows a master controller to figure out who is in the network for later communication. */
typedef struct _ichnaea_GetIdRequest {
    mbed_rpc_Header header;
} ichnaea_GetIdRequest;

/* Response to the GetIdRequest message. This contains the unique identifier of the node and a software
 version to help with compatibility decisions. */
typedef struct _ichnaea_GetIdResponse {
    mbed_rpc_Header header;
    uint32_t unique_id;
    uint8_t ver_major;
    uint8_t ver_minor;
    uint8_t ver_patch;
} ichnaea_GetIdResponse;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _ichnaea_Service_MIN ichnaea_Service_SVC_IDENTITY
#define _ichnaea_Service_MAX ichnaea_Service_SVC_IDENTITY
#define _ichnaea_Service_ARRAYSIZE ((ichnaea_Service)(ichnaea_Service_SVC_IDENTITY+1))

#define _ichnaea_Message_MIN ichnaea_Message_MSG_GET_ID_REQ
#define _ichnaea_Message_MAX ichnaea_Message_MSG_GET_ID_RSP
#define _ichnaea_Message_ARRAYSIZE ((ichnaea_Message)(ichnaea_Message_MSG_GET_ID_RSP+1))

#define _ichnaea_MessageVersion_MIN ichnaea_MessageVersion_MSG_VER_GET_ID_REQ
#define _ichnaea_MessageVersion_MAX ichnaea_MessageVersion_MSG_VER_GET_ID_RSP
#define _ichnaea_MessageVersion_ARRAYSIZE ((ichnaea_MessageVersion)(ichnaea_MessageVersion_MSG_VER_GET_ID_RSP+1))




/* Initializer values for message structs */
#define ichnaea_GetIdRequest_init_default        {mbed_rpc_Header_init_default}
#define ichnaea_GetIdResponse_init_default       {mbed_rpc_Header_init_default, 0, 0, 0, 0}
#define ichnaea_GetIdRequest_init_zero           {mbed_rpc_Header_init_zero}
#define ichnaea_GetIdResponse_init_zero          {mbed_rpc_Header_init_zero, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define ichnaea_GetIdRequest_header_tag          1
#define ichnaea_GetIdResponse_header_tag         1
#define ichnaea_GetIdResponse_unique_id_tag      2
#define ichnaea_GetIdResponse_ver_major_tag      3
#define ichnaea_GetIdResponse_ver_minor_tag      4
#define ichnaea_GetIdResponse_ver_patch_tag      5

/* Struct field encoding specification for nanopb */
#define ichnaea_GetIdRequest_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  header,            1)
#define ichnaea_GetIdRequest_CALLBACK NULL
#define ichnaea_GetIdRequest_DEFAULT NULL
#define ichnaea_GetIdRequest_header_MSGTYPE mbed_rpc_Header

#define ichnaea_GetIdResponse_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  header,            1) \
X(a, STATIC,   REQUIRED, UINT32,   unique_id,         2) \
X(a, STATIC,   REQUIRED, UINT32,   ver_major,         3) \
X(a, STATIC,   REQUIRED, UINT32,   ver_minor,         4) \
X(a, STATIC,   REQUIRED, UINT32,   ver_patch,         5)
#define ichnaea_GetIdResponse_CALLBACK NULL
#define ichnaea_GetIdResponse_DEFAULT NULL
#define ichnaea_GetIdResponse_header_MSGTYPE mbed_rpc_Header

extern const pb_msgdesc_t ichnaea_GetIdRequest_msg;
extern const pb_msgdesc_t ichnaea_GetIdResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define ichnaea_GetIdRequest_fields &ichnaea_GetIdRequest_msg
#define ichnaea_GetIdResponse_fields &ichnaea_GetIdResponse_msg

/* Maximum encoded size of messages (where known) */
#define ICHNAEA_ICHNAEA_PB_H_MAX_SIZE            ichnaea_GetIdResponse_size
#define ichnaea_GetIdRequest_size                14
#define ichnaea_GetIdResponse_size               29

#ifdef __cplusplus
} /* extern "C" */
#endif

#ifdef __cplusplus
/* Message descriptors for nanopb */
namespace nanopb {
template <>
struct MessageDescriptor<ichnaea_GetIdRequest> {
    static PB_INLINE_CONSTEXPR const pb_size_t fields_array_length = 1;
    static inline const pb_msgdesc_t* fields() {
        return &ichnaea_GetIdRequest_msg;
    }
};
template <>
struct MessageDescriptor<ichnaea_GetIdResponse> {
    static PB_INLINE_CONSTEXPR const pb_size_t fields_array_length = 5;
    static inline const pb_msgdesc_t* fields() {
        return &ichnaea_GetIdResponse_msg;
    }
};
}  // namespace nanopb

#endif  /* __cplusplus */


#endif
