# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sim_intf.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'sim_intf.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0esim_intf.proto\x12\x03sim\x1a\x1bgoogle/protobuf/empty.proto\"#\n\x12\x46loatingPointValue\x12\r\n\x05value\x18\x01 \x01(\x02\x32\x8e\x05\n\x12\x45nvironmentSpoofer\x12G\n\x12\x41pplyResistiveLoad\x12\x17.sim.FloatingPointValue\x1a\x16.google.protobuf.Empty\"\x00\x12@\n\x0bSetSolarOCV\x12\x17.sim.FloatingPointValue\x1a\x16.google.protobuf.Empty\"\x00\x12\x44\n\x0fSetBoard12VRail\x12\x17.sim.FloatingPointValue\x1a\x16.google.protobuf.Empty\"\x00\x12\x43\n\x0eSetBoard5VRail\x12\x17.sim.FloatingPointValue\x1a\x16.google.protobuf.Empty\"\x00\x12\x44\n\x0fSetBoard3V3Rail\x12\x17.sim.FloatingPointValue\x1a\x16.google.protobuf.Empty\"\x00\x12\x44\n\x0fSetBoard1V1Rail\x12\x17.sim.FloatingPointValue\x1a\x16.google.protobuf.Empty\"\x00\x12H\n\x13SetBoardTemperature\x12\x17.sim.FloatingPointValue\x1a\x16.google.protobuf.Empty\"\x00\x12\x45\n\x10SetBoardFanSpeed\x12\x17.sim.FloatingPointValue\x1a\x16.google.protobuf.Empty\"\x00\x12\x45\n\x10SetOutputVoltage\x12\x17.sim.FloatingPointValue\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sim_intf_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FLOATINGPOINTVALUE']._serialized_start=52
  _globals['_FLOATINGPOINTVALUE']._serialized_end=87
  _globals['_ENVIRONMENTSPOOFER']._serialized_start=90
  _globals['_ENVIRONMENTSPOOFER']._serialized_end=744
# @@protoc_insertion_point(module_scope)
