# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ichnaea_pdi.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'ichnaea_pdi.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import nanopb_pb2 as nanopb__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11ichnaea_pdi.proto\x12\x07ichnaea\x1a\x0cnanopb.proto\"*\n\rPDI_BootCount\x12\x19\n\nboot_count\x18\x01 \x02(\rB\x05\x92?\x02\x38 ')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ichnaea_pdi_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PDI_BOOTCOUNT'].fields_by_name['boot_count']._loaded_options = None
  _globals['_PDI_BOOTCOUNT'].fields_by_name['boot_count']._serialized_options = b'\222?\0028 '
  _globals['_PDI_BOOTCOUNT']._serialized_start=44
  _globals['_PDI_BOOTCOUNT']._serialized_end=86
# @@protoc_insertion_point(module_scope)
