"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import mbed_rpc_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _Service:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ServiceEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_Service.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    SVC_IDENTITY: _Service.ValueType  # 0

class Service(_Service, metaclass=_ServiceEnumTypeWrapper):
    """System services that are available to all nodes in the network."""

SVC_IDENTITY: Service.ValueType  # 0
global___Service = Service

class _Message:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _MessageEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_Message.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    MSG_GET_ID_REQ: _Message.ValueType  # 0
    MSG_GET_ID_RSP: _Message.ValueType  # 1

class Message(_Message, metaclass=_MessageEnumTypeWrapper):
    """Message types available"""

MSG_GET_ID_REQ: Message.ValueType  # 0
MSG_GET_ID_RSP: Message.ValueType  # 1
global___Message = Message

class _MessageVersion:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _MessageVersionEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_MessageVersion.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    MSG_VER_GET_ID_REQ: _MessageVersion.ValueType  # 0
    MSG_VER_GET_ID_RSP: _MessageVersion.ValueType  # 0

class MessageVersion(_MessageVersion, metaclass=_MessageVersionEnumTypeWrapper):
    """Version of the message. This is used to ensure that the message is compatible with the receiver."""

MSG_VER_GET_ID_REQ: MessageVersion.ValueType  # 0
MSG_VER_GET_ID_RSP: MessageVersion.ValueType  # 0
global___MessageVersion = MessageVersion

@typing.final
class GetIdRequest(google.protobuf.message.Message):
    """This is a broadcasted message to all nodes in the network to respond with their unique identifier.
    This allows a master controller to figure out who is in the network for later communication.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HEADER_FIELD_NUMBER: builtins.int
    @property
    def header(self) -> mbed_rpc_pb2.Header: ...
    def __init__(
        self,
        *,
        header: mbed_rpc_pb2.Header | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["header", b"header"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["header", b"header"]) -> None: ...

global___GetIdRequest = GetIdRequest

@typing.final
class GetIdResponse(google.protobuf.message.Message):
    """Response to the GetIdRequest message. This contains the unique identifier of the node and a software
    version to help with compatibility decisions.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HEADER_FIELD_NUMBER: builtins.int
    UNIQUE_ID_FIELD_NUMBER: builtins.int
    VER_MAJOR_FIELD_NUMBER: builtins.int
    VER_MINOR_FIELD_NUMBER: builtins.int
    VER_PATCH_FIELD_NUMBER: builtins.int
    unique_id: builtins.int
    ver_major: builtins.int
    ver_minor: builtins.int
    ver_patch: builtins.int
    @property
    def header(self) -> mbed_rpc_pb2.Header: ...
    def __init__(
        self,
        *,
        header: mbed_rpc_pb2.Header | None = ...,
        unique_id: builtins.int | None = ...,
        ver_major: builtins.int | None = ...,
        ver_minor: builtins.int | None = ...,
        ver_patch: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["header", b"header", "unique_id", b"unique_id", "ver_major", b"ver_major", "ver_minor", b"ver_minor", "ver_patch", b"ver_patch"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["header", b"header", "unique_id", b"unique_id", "ver_major", b"ver_major", "ver_minor", b"ver_minor", "ver_patch", b"ver_patch"]) -> None: ...

global___GetIdResponse = GetIdResponse
