"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class PDI_BootCount(google.protobuf.message.Message):
    """KEY_BOOT_COUNT"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BOOT_COUNT_FIELD_NUMBER: builtins.int
    boot_count: builtins.int
    def __init__(
        self,
        *,
        boot_count: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["boot_count", b"boot_count"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["boot_count", b"boot_count"]) -> None: ...

global___PDI_BootCount = PDI_BootCount
