"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import mbed_rpc_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _Service:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ServiceEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_Service.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    SVC_IDENTITY: _Service.ValueType  # 100
    """Get the unique system identifiers"""
    SVC_SETPOINT: _Service.ValueType  # 101
    """Control operational setpoints"""
    SVC_MANAGER: _Service.ValueType  # 102
    """Control system services"""
    SVC_SENSOR: _Service.ValueType  # 103
    """Read sensor values"""
    SVC_PING_NODE: _Service.ValueType  # 104
    """Ping a node to check if it is alive"""
    SVC_LTC_REG_GET: _Service.ValueType  # 105
    """Get a specific register on the LTC7871"""
    SVC_LTC_REG_SET: _Service.ValueType  # 106
    """Set a specific register on the LTC7871"""
    SVC_PDI_READ: _Service.ValueType  # 107
    """Read PDI data from the node"""
    SVC_PDI_WRITE: _Service.ValueType  # 108
    """Write PDI data to the node"""
    SVC_SYSTEM_STATUS: _Service.ValueType  # 109
    """Get the system status"""

class Service(_Service, metaclass=_ServiceEnumTypeWrapper):
    """System services that are available to all nodes in the network."""

SVC_IDENTITY: Service.ValueType  # 100
"""Get the unique system identifiers"""
SVC_SETPOINT: Service.ValueType  # 101
"""Control operational setpoints"""
SVC_MANAGER: Service.ValueType  # 102
"""Control system services"""
SVC_SENSOR: Service.ValueType  # 103
"""Read sensor values"""
SVC_PING_NODE: Service.ValueType  # 104
"""Ping a node to check if it is alive"""
SVC_LTC_REG_GET: Service.ValueType  # 105
"""Get a specific register on the LTC7871"""
SVC_LTC_REG_SET: Service.ValueType  # 106
"""Set a specific register on the LTC7871"""
SVC_PDI_READ: Service.ValueType  # 107
"""Read PDI data from the node"""
SVC_PDI_WRITE: Service.ValueType  # 108
"""Write PDI data to the node"""
SVC_SYSTEM_STATUS: Service.ValueType  # 109
"""Get the system status"""
global___Service = Service

class _Message:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _MessageEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_Message.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    MSG_GET_ID_REQ: _Message.ValueType  # 100
    """Request the unique system identifiers"""
    MSG_GET_ID_RSP: _Message.ValueType  # 101
    """Response to the GetIdRequest message"""
    MSG_SETPOINT_REQ: _Message.ValueType  # 102
    """Request to set operational setpoints"""
    MSG_SETPOINT_RSP: _Message.ValueType  # 103
    """Response to the SetpointRequest message"""
    MSG_MANAGER_REQ: _Message.ValueType  # 104
    """Request to control system services"""
    MSG_MANAGER_RSP: _Message.ValueType  # 105
    """Response to the SystemManagerRequest message"""
    MSG_SENSOR_REQ: _Message.ValueType  # 106
    """Request to read sensor values"""
    MSG_SENSOR_RSP: _Message.ValueType  # 107
    """Response to the SensorObserverRequest message"""
    MSG_PING_NODE_REQ: _Message.ValueType  # 108
    """Request to ping a node"""
    MSG_PING_NODE_RSP: _Message.ValueType  # 109
    """Response to the PingNodeRequest message"""
    MSG_PDI_READ_REQ: _Message.ValueType  # 114
    """Request to read PDI data from the node"""
    MSG_PDI_READ_RSP: _Message.ValueType  # 115
    """Response to the PDI read request"""
    MSG_PDI_WRITE_REQ: _Message.ValueType  # 116
    """Request to write PDI data to the node"""
    MSG_PDI_WRITE_RSP: _Message.ValueType  # 117
    """Response to the PDI write request"""
    MSG_SYSTEM_STATUS_REQ: _Message.ValueType  # 118
    """Request the system status"""
    MSG_SYSTEM_STATUS_RSP: _Message.ValueType  # 119
    """Response to the GetSysStatusRequest message"""

class Message(_Message, metaclass=_MessageEnumTypeWrapper):
    """Message types available. These start at 100 to avoid conflicts with the
    mbed_rpc.proto messages.
    """

MSG_GET_ID_REQ: Message.ValueType  # 100
"""Request the unique system identifiers"""
MSG_GET_ID_RSP: Message.ValueType  # 101
"""Response to the GetIdRequest message"""
MSG_SETPOINT_REQ: Message.ValueType  # 102
"""Request to set operational setpoints"""
MSG_SETPOINT_RSP: Message.ValueType  # 103
"""Response to the SetpointRequest message"""
MSG_MANAGER_REQ: Message.ValueType  # 104
"""Request to control system services"""
MSG_MANAGER_RSP: Message.ValueType  # 105
"""Response to the SystemManagerRequest message"""
MSG_SENSOR_REQ: Message.ValueType  # 106
"""Request to read sensor values"""
MSG_SENSOR_RSP: Message.ValueType  # 107
"""Response to the SensorObserverRequest message"""
MSG_PING_NODE_REQ: Message.ValueType  # 108
"""Request to ping a node"""
MSG_PING_NODE_RSP: Message.ValueType  # 109
"""Response to the PingNodeRequest message"""
MSG_PDI_READ_REQ: Message.ValueType  # 114
"""Request to read PDI data from the node"""
MSG_PDI_READ_RSP: Message.ValueType  # 115
"""Response to the PDI read request"""
MSG_PDI_WRITE_REQ: Message.ValueType  # 116
"""Request to write PDI data to the node"""
MSG_PDI_WRITE_RSP: Message.ValueType  # 117
"""Response to the PDI write request"""
MSG_SYSTEM_STATUS_REQ: Message.ValueType  # 118
"""Request the system status"""
MSG_SYSTEM_STATUS_RSP: Message.ValueType  # 119
"""Response to the GetSysStatusRequest message"""
global___Message = Message

class _MessageVersion:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _MessageVersionEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_MessageVersion.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    MSG_VER_GET_ID_REQ: _MessageVersion.ValueType  # 0
    MSG_VER_GET_ID_RSP: _MessageVersion.ValueType  # 0
    MSG_VER_SETPOINT_REQ: _MessageVersion.ValueType  # 0
    MSG_VER_SETPOINT_RSP: _MessageVersion.ValueType  # 0
    MSG_VER_MANAGER_REQ: _MessageVersion.ValueType  # 0
    MSG_VER_MANAGER_RSP: _MessageVersion.ValueType  # 0
    MSG_VER_SENSOR_REQ: _MessageVersion.ValueType  # 0
    MSG_VER_SENSOR_RSP: _MessageVersion.ValueType  # 0
    MSG_VER_PING_NODE_REQ: _MessageVersion.ValueType  # 0
    MSG_VER_PING_NODE_RSP: _MessageVersion.ValueType  # 0
    MSG_VER_PDI_READ_REQ: _MessageVersion.ValueType  # 0
    MSG_VER_PDI_READ_RSP: _MessageVersion.ValueType  # 0
    MSG_VER_PDI_WRITE_REQ: _MessageVersion.ValueType  # 0
    MSG_VER_PDI_WRITE_RSP: _MessageVersion.ValueType  # 0
    MSG_VER_SYSTEM_STATUS_REQ: _MessageVersion.ValueType  # 0
    MSG_VER_SYSTEM_STATUS_RSP: _MessageVersion.ValueType  # 0

class MessageVersion(_MessageVersion, metaclass=_MessageVersionEnumTypeWrapper):
    """Version of the message. This is used to ensure that the message is compatible
    with the receiver.
    """

MSG_VER_GET_ID_REQ: MessageVersion.ValueType  # 0
MSG_VER_GET_ID_RSP: MessageVersion.ValueType  # 0
MSG_VER_SETPOINT_REQ: MessageVersion.ValueType  # 0
MSG_VER_SETPOINT_RSP: MessageVersion.ValueType  # 0
MSG_VER_MANAGER_REQ: MessageVersion.ValueType  # 0
MSG_VER_MANAGER_RSP: MessageVersion.ValueType  # 0
MSG_VER_SENSOR_REQ: MessageVersion.ValueType  # 0
MSG_VER_SENSOR_RSP: MessageVersion.ValueType  # 0
MSG_VER_PING_NODE_REQ: MessageVersion.ValueType  # 0
MSG_VER_PING_NODE_RSP: MessageVersion.ValueType  # 0
MSG_VER_PDI_READ_REQ: MessageVersion.ValueType  # 0
MSG_VER_PDI_READ_RSP: MessageVersion.ValueType  # 0
MSG_VER_PDI_WRITE_REQ: MessageVersion.ValueType  # 0
MSG_VER_PDI_WRITE_RSP: MessageVersion.ValueType  # 0
MSG_VER_SYSTEM_STATUS_REQ: MessageVersion.ValueType  # 0
MSG_VER_SYSTEM_STATUS_RSP: MessageVersion.ValueType  # 0
global___MessageVersion = MessageVersion

class _ManagerCommand:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ManagerCommandEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ManagerCommand.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    CMD_REBOOT: _ManagerCommand.ValueType  # 0
    """Reboot the node"""
    CMD_ENGAGE_OUTPUT: _ManagerCommand.ValueType  # 1
    """Enable power output from the node"""
    CMD_DISENGAGE_OUTPUT: _ManagerCommand.ValueType  # 2
    """Disable power output from the node"""
    CMD_FLUSH_PDI_CACHE: _ManagerCommand.ValueType  # 3
    """Flush the PDI database"""
    CMD_ZERO_OUTPUT_CURRENT: _ManagerCommand.ValueType  # 4
    """Zero the output current sensor"""

class ManagerCommand(_ManagerCommand, metaclass=_ManagerCommandEnumTypeWrapper):
    """****************************************************************************
    System Manager Service
    ****************************************************************************
    """

CMD_REBOOT: ManagerCommand.ValueType  # 0
"""Reboot the node"""
CMD_ENGAGE_OUTPUT: ManagerCommand.ValueType  # 1
"""Enable power output from the node"""
CMD_DISENGAGE_OUTPUT: ManagerCommand.ValueType  # 2
"""Disable power output from the node"""
CMD_FLUSH_PDI_CACHE: ManagerCommand.ValueType  # 3
"""Flush the PDI database"""
CMD_ZERO_OUTPUT_CURRENT: ManagerCommand.ValueType  # 4
"""Zero the output current sensor"""
global___ManagerCommand = ManagerCommand

class _ManagerError:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ManagerErrorEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ManagerError.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    ERR_CMD_NO_ERROR: _ManagerError.ValueType  # 0
    ERR_CMD_INVALID: _ManagerError.ValueType  # 1
    ERR_CMD_FAILED: _ManagerError.ValueType  # 2

class ManagerError(_ManagerError, metaclass=_ManagerErrorEnumTypeWrapper): ...

ERR_CMD_NO_ERROR: ManagerError.ValueType  # 0
ERR_CMD_INVALID: ManagerError.ValueType  # 1
ERR_CMD_FAILED: ManagerError.ValueType  # 2
global___ManagerError = ManagerError

class _SetpointError:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _SetpointErrorEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_SetpointError.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    ERR_SETPOINT_NO_ERROR: _SetpointError.ValueType  # 0
    ERR_SETPOINT_INVALID: _SetpointError.ValueType  # 1
    ERR_SETPOINT_NOT_SUPPORTED: _SetpointError.ValueType  # 2

class SetpointError(_SetpointError, metaclass=_SetpointErrorEnumTypeWrapper):
    """****************************************************************************
    Setpoint Service
    ****************************************************************************
    """

ERR_SETPOINT_NO_ERROR: SetpointError.ValueType  # 0
ERR_SETPOINT_INVALID: SetpointError.ValueType  # 1
ERR_SETPOINT_NOT_SUPPORTED: SetpointError.ValueType  # 2
global___SetpointError = SetpointError

class _SetpointField:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _SetpointFieldEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_SetpointField.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    SETPOINT_OUTPUT_VOLTAGE: _SetpointField.ValueType  # 0
    """Regulated output voltage of the node"""
    SETPOINT_MAX_AVG_OUTPUT_CURRENT: _SetpointField.ValueType  # 1
    """Maximum average output current of the node"""

class SetpointField(_SetpointField, metaclass=_SetpointFieldEnumTypeWrapper): ...

SETPOINT_OUTPUT_VOLTAGE: SetpointField.ValueType  # 0
"""Regulated output voltage of the node"""
SETPOINT_MAX_AVG_OUTPUT_CURRENT: SetpointField.ValueType  # 1
"""Maximum average output current of the node"""
global___SetpointField = SetpointField

class _SensorError:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _SensorErrorEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_SensorError.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    ERR_SENSOR_NO_ERROR: _SensorError.ValueType  # 0
    ERR_SENSOR_NOT_SUPPORTED: _SensorError.ValueType  # 1
    ERR_SENSOR_READ_FAILED: _SensorError.ValueType  # 2
    ERR_SENSOR_UNKNOWN: _SensorError.ValueType  # 3

class SensorError(_SensorError, metaclass=_SensorErrorEnumTypeWrapper):
    """****************************************************************************
    Sensor Observer Service
    ****************************************************************************
    """

ERR_SENSOR_NO_ERROR: SensorError.ValueType  # 0
ERR_SENSOR_NOT_SUPPORTED: SensorError.ValueType  # 1
ERR_SENSOR_READ_FAILED: SensorError.ValueType  # 2
ERR_SENSOR_UNKNOWN: SensorError.ValueType  # 3
global___SensorError = SensorError

class _SensorType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _SensorTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_SensorType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    SENSOR_OUTPUT_VOLTAGE: _SensorType.ValueType  # 0
    SENSOR_INPUT_VOLTAGE: _SensorType.ValueType  # 1
    SENSOR_OUTPUT_CURRENT: _SensorType.ValueType  # 2
    SENSOR_LTC_AVG_OUTPUT_CURRENT: _SensorType.ValueType  # 3
    SENSOR_BOARD_TEMP_1: _SensorType.ValueType  # 4
    SENSOR_BOARD_TEMP_2: _SensorType.ValueType  # 5
    SENSOR_BOARD_TEMP_3: _SensorType.ValueType  # 6
    SENSOR_VOLTAGE_MON_1V1: _SensorType.ValueType  # 7
    SENSOR_VOLTAGE_MON_3V3: _SensorType.ValueType  # 8
    SENSOR_VOLTAGE_MON_5V: _SensorType.ValueType  # 9
    SENSOR_VOLTAGE_MON_12V: _SensorType.ValueType  # 10

class SensorType(_SensorType, metaclass=_SensorTypeEnumTypeWrapper): ...

SENSOR_OUTPUT_VOLTAGE: SensorType.ValueType  # 0
SENSOR_INPUT_VOLTAGE: SensorType.ValueType  # 1
SENSOR_OUTPUT_CURRENT: SensorType.ValueType  # 2
SENSOR_LTC_AVG_OUTPUT_CURRENT: SensorType.ValueType  # 3
SENSOR_BOARD_TEMP_1: SensorType.ValueType  # 4
SENSOR_BOARD_TEMP_2: SensorType.ValueType  # 5
SENSOR_BOARD_TEMP_3: SensorType.ValueType  # 6
SENSOR_VOLTAGE_MON_1V1: SensorType.ValueType  # 7
SENSOR_VOLTAGE_MON_3V3: SensorType.ValueType  # 8
SENSOR_VOLTAGE_MON_5V: SensorType.ValueType  # 9
SENSOR_VOLTAGE_MON_12V: SensorType.ValueType  # 10
global___SensorType = SensorType

class _EngageState:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _EngageStateEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_EngageState.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    ENGAGED: _EngageState.ValueType  # 0
    """Power stage engaged and outputting power"""
    DISENGAGED: _EngageState.ValueType  # 1
    """Power stage disabled"""
    FAULTED: _EngageState.ValueType  # 2
    """Power stage faulted"""

class EngageState(_EngageState, metaclass=_EngageStateEnumTypeWrapper):
    """****************************************************************************
    System Status Service
    ****************************************************************************
    """

ENGAGED: EngageState.ValueType  # 0
"""Power stage engaged and outputting power"""
DISENGAGED: EngageState.ValueType  # 1
"""Power stage disabled"""
FAULTED: EngageState.ValueType  # 2
"""Power stage faulted"""
global___EngageState = EngageState

@typing.final
class PingNodeRequest(google.protobuf.message.Message):
    """****************************************************************************
    Ping Node Service
    ****************************************************************************
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HEADER_FIELD_NUMBER: builtins.int
    NODE_ID_FIELD_NUMBER: builtins.int
    node_id: builtins.int
    @property
    def header(self) -> mbed_rpc_pb2.Header: ...
    def __init__(
        self,
        *,
        header: mbed_rpc_pb2.Header | None = ...,
        node_id: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["header", b"header", "node_id", b"node_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["header", b"header", "node_id", b"node_id"]) -> None: ...

global___PingNodeRequest = PingNodeRequest

@typing.final
class PingNodeResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HEADER_FIELD_NUMBER: builtins.int
    @property
    def header(self) -> mbed_rpc_pb2.Header: ...
    def __init__(
        self,
        *,
        header: mbed_rpc_pb2.Header | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["header", b"header"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["header", b"header"]) -> None: ...

global___PingNodeResponse = PingNodeResponse

@typing.final
class GetIdRequest(google.protobuf.message.Message):
    """****************************************************************************
    Identity Service
    ****************************************************************************

    This is a broadcasted message to all nodes in the network to respond with
    their unique identifier. This allows a master controller to figure out who is
    in the network for later communication.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HEADER_FIELD_NUMBER: builtins.int
    @property
    def header(self) -> mbed_rpc_pb2.Header: ...
    def __init__(
        self,
        *,
        header: mbed_rpc_pb2.Header | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["header", b"header"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["header", b"header"]) -> None: ...

global___GetIdRequest = GetIdRequest

@typing.final
class GetIdResponse(google.protobuf.message.Message):
    """Response to the GetIdRequest message. This contains the unique identifier of
    the node and a software version to help with compatibility decisions.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HEADER_FIELD_NUMBER: builtins.int
    UNIQUE_ID_FIELD_NUMBER: builtins.int
    VER_MAJOR_FIELD_NUMBER: builtins.int
    VER_MINOR_FIELD_NUMBER: builtins.int
    VER_PATCH_FIELD_NUMBER: builtins.int
    unique_id: builtins.int
    ver_major: builtins.int
    ver_minor: builtins.int
    ver_patch: builtins.int
    @property
    def header(self) -> mbed_rpc_pb2.Header: ...
    def __init__(
        self,
        *,
        header: mbed_rpc_pb2.Header | None = ...,
        unique_id: builtins.int | None = ...,
        ver_major: builtins.int | None = ...,
        ver_minor: builtins.int | None = ...,
        ver_patch: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["header", b"header", "unique_id", b"unique_id", "ver_major", b"ver_major", "ver_minor", b"ver_minor", "ver_patch", b"ver_patch"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["header", b"header", "unique_id", b"unique_id", "ver_major", b"ver_major", "ver_minor", b"ver_minor", "ver_patch", b"ver_patch"]) -> None: ...

global___GetIdResponse = GetIdResponse

@typing.final
class ManagerRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HEADER_FIELD_NUMBER: builtins.int
    NODE_ID_FIELD_NUMBER: builtins.int
    COMMAND_FIELD_NUMBER: builtins.int
    node_id: builtins.int
    command: global___ManagerCommand.ValueType
    @property
    def header(self) -> mbed_rpc_pb2.Header: ...
    def __init__(
        self,
        *,
        header: mbed_rpc_pb2.Header | None = ...,
        node_id: builtins.int | None = ...,
        command: global___ManagerCommand.ValueType | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["command", b"command", "header", b"header", "node_id", b"node_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["command", b"command", "header", b"header", "node_id", b"node_id"]) -> None: ...

global___ManagerRequest = ManagerRequest

@typing.final
class ManagerResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HEADER_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    status: global___ManagerError.ValueType
    message: builtins.str
    @property
    def header(self) -> mbed_rpc_pb2.Header: ...
    def __init__(
        self,
        *,
        header: mbed_rpc_pb2.Header | None = ...,
        status: global___ManagerError.ValueType | None = ...,
        message: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["header", b"header", "message", b"message", "status", b"status"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["header", b"header", "message", b"message", "status", b"status"]) -> None: ...

global___ManagerResponse = ManagerResponse

@typing.final
class SetpointRequest(google.protobuf.message.Message):
    """Control a node's operational setpoints for parameters like voltage, current,
    etc.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HEADER_FIELD_NUMBER: builtins.int
    NODE_ID_FIELD_NUMBER: builtins.int
    FIELD_FIELD_NUMBER: builtins.int
    UINT32_TYPE_FIELD_NUMBER: builtins.int
    FLOAT_TYPE_FIELD_NUMBER: builtins.int
    node_id: builtins.int
    field: global___SetpointField.ValueType
    """Which field to set"""
    uint32_type: builtins.int
    float_type: builtins.float
    @property
    def header(self) -> mbed_rpc_pb2.Header: ...
    def __init__(
        self,
        *,
        header: mbed_rpc_pb2.Header | None = ...,
        node_id: builtins.int | None = ...,
        field: global___SetpointField.ValueType | None = ...,
        uint32_type: builtins.int | None = ...,
        float_type: builtins.float | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["field", b"field", "float_type", b"float_type", "header", b"header", "node_id", b"node_id", "uint32_type", b"uint32_type", "value_oneof", b"value_oneof"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["field", b"field", "float_type", b"float_type", "header", b"header", "node_id", b"node_id", "uint32_type", b"uint32_type", "value_oneof", b"value_oneof"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["value_oneof", b"value_oneof"]) -> typing.Literal["uint32_type", "float_type"] | None: ...

global___SetpointRequest = SetpointRequest

@typing.final
class SetpointResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HEADER_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    status: global___SetpointError.ValueType
    message: builtins.str
    @property
    def header(self) -> mbed_rpc_pb2.Header: ...
    def __init__(
        self,
        *,
        header: mbed_rpc_pb2.Header | None = ...,
        status: global___SetpointError.ValueType | None = ...,
        message: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["header", b"header", "message", b"message", "status", b"status"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["header", b"header", "message", b"message", "status", b"status"]) -> None: ...

global___SetpointResponse = SetpointResponse

@typing.final
class SensorRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HEADER_FIELD_NUMBER: builtins.int
    NODE_ID_FIELD_NUMBER: builtins.int
    SENSOR_FIELD_NUMBER: builtins.int
    node_id: builtins.int
    sensor: global___SensorType.ValueType
    @property
    def header(self) -> mbed_rpc_pb2.Header: ...
    def __init__(
        self,
        *,
        header: mbed_rpc_pb2.Header | None = ...,
        node_id: builtins.int | None = ...,
        sensor: global___SensorType.ValueType | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["header", b"header", "node_id", b"node_id", "sensor", b"sensor"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["header", b"header", "node_id", b"node_id", "sensor", b"sensor"]) -> None: ...

global___SensorRequest = SensorRequest

@typing.final
class SensorResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HEADER_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    status: global___SensorError.ValueType
    value: builtins.float
    @property
    def header(self) -> mbed_rpc_pb2.Header: ...
    def __init__(
        self,
        *,
        header: mbed_rpc_pb2.Header | None = ...,
        status: global___SensorError.ValueType | None = ...,
        value: builtins.float | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["header", b"header", "status", b"status", "value", b"value"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["header", b"header", "status", b"status", "value", b"value"]) -> None: ...

global___SensorResponse = SensorResponse

@typing.final
class PDIReadRequest(google.protobuf.message.Message):
    """****************************************************************************
    PDI Read Service
    ****************************************************************************
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HEADER_FIELD_NUMBER: builtins.int
    NODE_ID_FIELD_NUMBER: builtins.int
    PDI_ID_FIELD_NUMBER: builtins.int
    node_id: builtins.int
    pdi_id: builtins.int
    @property
    def header(self) -> mbed_rpc_pb2.Header: ...
    def __init__(
        self,
        *,
        header: mbed_rpc_pb2.Header | None = ...,
        node_id: builtins.int | None = ...,
        pdi_id: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["header", b"header", "node_id", b"node_id", "pdi_id", b"pdi_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["header", b"header", "node_id", b"node_id", "pdi_id", b"pdi_id"]) -> None: ...

global___PDIReadRequest = PDIReadRequest

@typing.final
class PDIReadResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HEADER_FIELD_NUMBER: builtins.int
    SUCCESS_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    success: builtins.bool
    data: builtins.bytes
    @property
    def header(self) -> mbed_rpc_pb2.Header: ...
    def __init__(
        self,
        *,
        header: mbed_rpc_pb2.Header | None = ...,
        success: builtins.bool | None = ...,
        data: builtins.bytes | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["data", b"data", "header", b"header", "success", b"success"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["data", b"data", "header", b"header", "success", b"success"]) -> None: ...

global___PDIReadResponse = PDIReadResponse

@typing.final
class PDIWriteRequest(google.protobuf.message.Message):
    """****************************************************************************
    PDI Write Service
    ****************************************************************************
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HEADER_FIELD_NUMBER: builtins.int
    NODE_ID_FIELD_NUMBER: builtins.int
    PDI_ID_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    node_id: builtins.int
    pdi_id: builtins.int
    data: builtins.bytes
    @property
    def header(self) -> mbed_rpc_pb2.Header: ...
    def __init__(
        self,
        *,
        header: mbed_rpc_pb2.Header | None = ...,
        node_id: builtins.int | None = ...,
        pdi_id: builtins.int | None = ...,
        data: builtins.bytes | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["data", b"data", "header", b"header", "node_id", b"node_id", "pdi_id", b"pdi_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["data", b"data", "header", b"header", "node_id", b"node_id", "pdi_id", b"pdi_id"]) -> None: ...

global___PDIWriteRequest = PDIWriteRequest

@typing.final
class PDIWriteResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HEADER_FIELD_NUMBER: builtins.int
    SUCCESS_FIELD_NUMBER: builtins.int
    success: builtins.bool
    @property
    def header(self) -> mbed_rpc_pb2.Header: ...
    def __init__(
        self,
        *,
        header: mbed_rpc_pb2.Header | None = ...,
        success: builtins.bool | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["header", b"header", "success", b"success"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["header", b"header", "success", b"success"]) -> None: ...

global___PDIWriteResponse = PDIWriteResponse

@typing.final
class SystemStatusRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HEADER_FIELD_NUMBER: builtins.int
    NODE_ID_FIELD_NUMBER: builtins.int
    node_id: builtins.int
    @property
    def header(self) -> mbed_rpc_pb2.Header: ...
    def __init__(
        self,
        *,
        header: mbed_rpc_pb2.Header | None = ...,
        node_id: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["header", b"header", "node_id", b"node_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["header", b"header", "node_id", b"node_id"]) -> None: ...

global___SystemStatusRequest = SystemStatusRequest

@typing.final
class SystemStatusResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HEADER_FIELD_NUMBER: builtins.int
    TIMESTAMP_FIELD_NUMBER: builtins.int
    OUTPUT_STATE_FIELD_NUMBER: builtins.int
    timestamp: builtins.int
    """System time in ms"""
    output_state: global___EngageState.ValueType
    """Power stage output state"""
    @property
    def header(self) -> mbed_rpc_pb2.Header: ...
    def __init__(
        self,
        *,
        header: mbed_rpc_pb2.Header | None = ...,
        timestamp: builtins.int | None = ...,
        output_state: global___EngageState.ValueType | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["header", b"header", "output_state", b"output_state", "timestamp", b"timestamp"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["header", b"header", "output_state", b"output_state", "timestamp", b"timestamp"]) -> None: ...

global___SystemStatusResponse = SystemStatusResponse
