# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ichnaea_async.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'ichnaea_async.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import nanopb_pb2 as nanopb__pb2
import mbed_rpc_pb2 as mbed__rpc__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13ichnaea_async.proto\x12\x07ichnaea\x1a\x0cnanopb.proto\x1a\x0embed_rpc.proto\"z\n\tHeartbeat\x12 \n\x06header\x18\x01 \x02(\x0b\x32\x10.mbed.rpc.Header\x12\x19\n\nboot_count\x18\x02 \x02(\rB\x05\x92?\x02\x38 \x12\x16\n\x07node_id\x18\x03 \x02(\rB\x05\x92?\x02\x38 \x12\x18\n\ttimestamp\x18\x04 \x02(\rB\x05\x92?\x02\x38 *$\n\x0e\x41syncMessageId\x12\x12\n\rMSG_HEARTBEAT\x10\xc8\x01*,\n\x13\x41syncMessageVersion\x12\x15\n\x11MSG_VER_HEARTBEAT\x10\x00')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ichnaea_async_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEARTBEAT'].fields_by_name['boot_count']._loaded_options = None
  _globals['_HEARTBEAT'].fields_by_name['boot_count']._serialized_options = b'\222?\0028 '
  _globals['_HEARTBEAT'].fields_by_name['node_id']._loaded_options = None
  _globals['_HEARTBEAT'].fields_by_name['node_id']._serialized_options = b'\222?\0028 '
  _globals['_HEARTBEAT'].fields_by_name['timestamp']._loaded_options = None
  _globals['_HEARTBEAT'].fields_by_name['timestamp']._serialized_options = b'\222?\0028 '
  _globals['_ASYNCMESSAGEID']._serialized_start=186
  _globals['_ASYNCMESSAGEID']._serialized_end=222
  _globals['_ASYNCMESSAGEVERSION']._serialized_start=224
  _globals['_ASYNCMESSAGEVERSION']._serialized_end=268
  _globals['_HEARTBEAT']._serialized_start=62
  _globals['_HEARTBEAT']._serialized_end=184
# @@protoc_insertion_point(module_scope)
