"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import mbed_rpc_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _Service:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ServiceEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_Service.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    SVC_IDENTITY: _Service.ValueType  # 100
    """Get the unique system identifiers"""
    SVC_SETPOINT: _Service.ValueType  # 101
    """Control operational setpoints"""
    SVC_MANAGER: _Service.ValueType  # 102
    """Control system services"""
    SVC_SENSOR: _Service.ValueType  # 103
    """Read sensor values"""
    SVC_PING_NODE: _Service.ValueType  # 104
    """Ping a node to check if it is alive"""
    SVC_LTC_REG_GET: _Service.ValueType  # 105
    """Get a specific register on the LTC7871"""
    SVC_LTC_REG_SET: _Service.ValueType  # 106
    """Set a specific register on the LTC7871"""

class Service(_Service, metaclass=_ServiceEnumTypeWrapper):
    """System services that are available to all nodes in the network."""

SVC_IDENTITY: Service.ValueType  # 100
"""Get the unique system identifiers"""
SVC_SETPOINT: Service.ValueType  # 101
"""Control operational setpoints"""
SVC_MANAGER: Service.ValueType  # 102
"""Control system services"""
SVC_SENSOR: Service.ValueType  # 103
"""Read sensor values"""
SVC_PING_NODE: Service.ValueType  # 104
"""Ping a node to check if it is alive"""
SVC_LTC_REG_GET: Service.ValueType  # 105
"""Get a specific register on the LTC7871"""
SVC_LTC_REG_SET: Service.ValueType  # 106
"""Set a specific register on the LTC7871"""
global___Service = Service

class _Message:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _MessageEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_Message.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    MSG_GET_ID_REQ: _Message.ValueType  # 100
    """Request the unique system identifiers"""
    MSG_GET_ID_RSP: _Message.ValueType  # 101
    """Response to the GetIdRequest message"""
    MSG_SETPOINT_REQ: _Message.ValueType  # 102
    """Request to set operational setpoints"""
    MSG_SETPOINT_RSP: _Message.ValueType  # 103
    """Response to the SetpointRequest message"""
    MSG_MANAGER_REQ: _Message.ValueType  # 104
    """Request to control system services"""
    MSG_MANAGER_RSP: _Message.ValueType  # 105
    """Response to the SystemManagerRequest message"""
    MSG_SENSOR_REQ: _Message.ValueType  # 106
    """Request to read sensor values"""
    MSG_SENSOR_RSP: _Message.ValueType  # 107
    """Response to the SensorObserverRequest message"""
    MSG_PING_NODE_REQ: _Message.ValueType  # 108
    """Request to ping a node"""
    MSG_PING_NODE_RSP: _Message.ValueType  # 109
    """Response to the PingNodeRequest message"""
    MSG_LTC_REG_SET_REQ: _Message.ValueType  # 110
    """Request to set a specific register on the LTC7871"""
    MSG_LTC_REG_SET_RSP: _Message.ValueType  # 111
    """Response to a register set command"""
    MSG_LTC_REG_GET_REQ: _Message.ValueType  # 112
    """Request to get a specific register on the LTC7871"""
    MSG_LTC_REG_GET_RSP: _Message.ValueType  # 113
    """Response to a register get command"""

class Message(_Message, metaclass=_MessageEnumTypeWrapper):
    """Message types available"""

MSG_GET_ID_REQ: Message.ValueType  # 100
"""Request the unique system identifiers"""
MSG_GET_ID_RSP: Message.ValueType  # 101
"""Response to the GetIdRequest message"""
MSG_SETPOINT_REQ: Message.ValueType  # 102
"""Request to set operational setpoints"""
MSG_SETPOINT_RSP: Message.ValueType  # 103
"""Response to the SetpointRequest message"""
MSG_MANAGER_REQ: Message.ValueType  # 104
"""Request to control system services"""
MSG_MANAGER_RSP: Message.ValueType  # 105
"""Response to the SystemManagerRequest message"""
MSG_SENSOR_REQ: Message.ValueType  # 106
"""Request to read sensor values"""
MSG_SENSOR_RSP: Message.ValueType  # 107
"""Response to the SensorObserverRequest message"""
MSG_PING_NODE_REQ: Message.ValueType  # 108
"""Request to ping a node"""
MSG_PING_NODE_RSP: Message.ValueType  # 109
"""Response to the PingNodeRequest message"""
MSG_LTC_REG_SET_REQ: Message.ValueType  # 110
"""Request to set a specific register on the LTC7871"""
MSG_LTC_REG_SET_RSP: Message.ValueType  # 111
"""Response to a register set command"""
MSG_LTC_REG_GET_REQ: Message.ValueType  # 112
"""Request to get a specific register on the LTC7871"""
MSG_LTC_REG_GET_RSP: Message.ValueType  # 113
"""Response to a register get command"""
global___Message = Message

class _MessageVersion:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _MessageVersionEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_MessageVersion.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    MSG_VER_GET_ID_REQ: _MessageVersion.ValueType  # 0
    MSG_VER_GET_ID_RSP: _MessageVersion.ValueType  # 0
    MSG_VER_SETPOINT_REQ: _MessageVersion.ValueType  # 0
    MSG_VER_SETPOINT_RSP: _MessageVersion.ValueType  # 0
    MSG_VER_MANAGER_REQ: _MessageVersion.ValueType  # 0
    MSG_VER_MANAGER_RSP: _MessageVersion.ValueType  # 0
    MSG_VER_SENSOR_REQ: _MessageVersion.ValueType  # 0
    MSG_VER_SENSOR_RSP: _MessageVersion.ValueType  # 0
    MSG_VER_PING_NODE_REQ: _MessageVersion.ValueType  # 0
    MSG_VER_PING_NODE_RSP: _MessageVersion.ValueType  # 0
    MSG_VER_LTC_REG_SET_REQ: _MessageVersion.ValueType  # 0
    MSG_VER_LTC_REG_SET_RSP: _MessageVersion.ValueType  # 0
    MSG_VER_LTC_REG_GET_REQ: _MessageVersion.ValueType  # 0
    MSG_VER_LTC_REG_GET_RSP: _MessageVersion.ValueType  # 0

class MessageVersion(_MessageVersion, metaclass=_MessageVersionEnumTypeWrapper):
    """Version of the message. This is used to ensure that the message is compatible with the receiver."""

MSG_VER_GET_ID_REQ: MessageVersion.ValueType  # 0
MSG_VER_GET_ID_RSP: MessageVersion.ValueType  # 0
MSG_VER_SETPOINT_REQ: MessageVersion.ValueType  # 0
MSG_VER_SETPOINT_RSP: MessageVersion.ValueType  # 0
MSG_VER_MANAGER_REQ: MessageVersion.ValueType  # 0
MSG_VER_MANAGER_RSP: MessageVersion.ValueType  # 0
MSG_VER_SENSOR_REQ: MessageVersion.ValueType  # 0
MSG_VER_SENSOR_RSP: MessageVersion.ValueType  # 0
MSG_VER_PING_NODE_REQ: MessageVersion.ValueType  # 0
MSG_VER_PING_NODE_RSP: MessageVersion.ValueType  # 0
MSG_VER_LTC_REG_SET_REQ: MessageVersion.ValueType  # 0
MSG_VER_LTC_REG_SET_RSP: MessageVersion.ValueType  # 0
MSG_VER_LTC_REG_GET_REQ: MessageVersion.ValueType  # 0
MSG_VER_LTC_REG_GET_RSP: MessageVersion.ValueType  # 0
global___MessageVersion = MessageVersion

class _ManagerCommand:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ManagerCommandEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ManagerCommand.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    CMD_REBOOT: _ManagerCommand.ValueType  # 0
    """Reboot the node"""
    CMD_ENGAGE_OUTPUT: _ManagerCommand.ValueType  # 1
    """Enable power output from the node"""
    CMD_DISENGAGE_OUTPUT: _ManagerCommand.ValueType  # 2
    """Disable power output from the node"""

class ManagerCommand(_ManagerCommand, metaclass=_ManagerCommandEnumTypeWrapper):
    """****************************************************************************
    System Manager Service
    ****************************************************************************
    """

CMD_REBOOT: ManagerCommand.ValueType  # 0
"""Reboot the node"""
CMD_ENGAGE_OUTPUT: ManagerCommand.ValueType  # 1
"""Enable power output from the node"""
CMD_DISENGAGE_OUTPUT: ManagerCommand.ValueType  # 2
"""Disable power output from the node"""
global___ManagerCommand = ManagerCommand

class _ManagerError:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ManagerErrorEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ManagerError.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    ERR_CMD_NO_ERROR: _ManagerError.ValueType  # 0
    ERR_CMD_INVALID: _ManagerError.ValueType  # 1
    ERR_CMD_FAILED: _ManagerError.ValueType  # 2

class ManagerError(_ManagerError, metaclass=_ManagerErrorEnumTypeWrapper): ...

ERR_CMD_NO_ERROR: ManagerError.ValueType  # 0
ERR_CMD_INVALID: ManagerError.ValueType  # 1
ERR_CMD_FAILED: ManagerError.ValueType  # 2
global___ManagerError = ManagerError

class _SetpointError:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _SetpointErrorEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_SetpointError.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    ERR_SETPOINT_NO_ERROR: _SetpointError.ValueType  # 0
    ERR_SETPOINT_INVALID: _SetpointError.ValueType  # 1
    ERR_SETPOINT_NOT_SUPPORTED: _SetpointError.ValueType  # 2

class SetpointError(_SetpointError, metaclass=_SetpointErrorEnumTypeWrapper):
    """****************************************************************************
    Setpoint Service
    ****************************************************************************
    """

ERR_SETPOINT_NO_ERROR: SetpointError.ValueType  # 0
ERR_SETPOINT_INVALID: SetpointError.ValueType  # 1
ERR_SETPOINT_NOT_SUPPORTED: SetpointError.ValueType  # 2
global___SetpointError = SetpointError

class _SetpointField:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _SetpointFieldEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_SetpointField.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    SETPOINT_OUTPUT_VOLTAGE: _SetpointField.ValueType  # 0
    """Regulated output voltage of the node"""
    SETPOINT_MAX_AVG_OUTPUT_CURRENT: _SetpointField.ValueType  # 1
    """Maximum average output current of the node"""

class SetpointField(_SetpointField, metaclass=_SetpointFieldEnumTypeWrapper): ...

SETPOINT_OUTPUT_VOLTAGE: SetpointField.ValueType  # 0
"""Regulated output voltage of the node"""
SETPOINT_MAX_AVG_OUTPUT_CURRENT: SetpointField.ValueType  # 1
"""Maximum average output current of the node"""
global___SetpointField = SetpointField

class _SensorError:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _SensorErrorEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_SensorError.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    ERR_SENSOR_NO_ERROR: _SensorError.ValueType  # 0
    ERR_SENSOR_NOT_SUPPORTED: _SensorError.ValueType  # 1
    ERR_SENSOR_READ_FAILED: _SensorError.ValueType  # 2
    ERR_SENSOR_UNKNOWN: _SensorError.ValueType  # 3

class SensorError(_SensorError, metaclass=_SensorErrorEnumTypeWrapper):
    """****************************************************************************
    Sensor Observer Service
    ****************************************************************************
    """

ERR_SENSOR_NO_ERROR: SensorError.ValueType  # 0
ERR_SENSOR_NOT_SUPPORTED: SensorError.ValueType  # 1
ERR_SENSOR_READ_FAILED: SensorError.ValueType  # 2
ERR_SENSOR_UNKNOWN: SensorError.ValueType  # 3
global___SensorError = SensorError

class _SensorType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _SensorTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_SensorType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    SENSOR_OUTPUT_VOLTAGE: _SensorType.ValueType  # 0
    SENSOR_INPUT_VOLTAGE: _SensorType.ValueType  # 1
    SENSOR_AVG_OUTPUT_CURRENT: _SensorType.ValueType  # 2
    SENSOR_BOARD_TEMP_1: _SensorType.ValueType  # 3
    SENSOR_BOARD_TEMP_2: _SensorType.ValueType  # 4
    SENSOR_BOARD_TEMP_3: _SensorType.ValueType  # 5

class SensorType(_SensorType, metaclass=_SensorTypeEnumTypeWrapper): ...

SENSOR_OUTPUT_VOLTAGE: SensorType.ValueType  # 0
SENSOR_INPUT_VOLTAGE: SensorType.ValueType  # 1
SENSOR_AVG_OUTPUT_CURRENT: SensorType.ValueType  # 2
SENSOR_BOARD_TEMP_1: SensorType.ValueType  # 3
SENSOR_BOARD_TEMP_2: SensorType.ValueType  # 4
SENSOR_BOARD_TEMP_3: SensorType.ValueType  # 5
global___SensorType = SensorType

class _LTCRegisterError:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _LTCRegisterErrorEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_LTCRegisterError.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    ERR_LTC_REG_NO_ERROR: _LTCRegisterError.ValueType  # 0
    """No error"""
    ERR_LTC_REG_INVALID: _LTCRegisterError.ValueType  # 1
    """Invalid register requested"""
    ERR_LTC_REG_BAD_VALUE: _LTCRegisterError.ValueType  # 2
    """Bad value for the register"""
    ERR_LTC_REG_READ_ONLY: _LTCRegisterError.ValueType  # 3
    """Register is read-only"""
    ERR_LTC_ACCESS_FAILED: _LTCRegisterError.ValueType  # 4
    """LTC7871 access failed/unavailable"""

class LTCRegisterError(_LTCRegisterError, metaclass=_LTCRegisterErrorEnumTypeWrapper):
    """****************************************************************************
    LTC Register Set Service
    ****************************************************************************
    """

ERR_LTC_REG_NO_ERROR: LTCRegisterError.ValueType  # 0
"""No error"""
ERR_LTC_REG_INVALID: LTCRegisterError.ValueType  # 1
"""Invalid register requested"""
ERR_LTC_REG_BAD_VALUE: LTCRegisterError.ValueType  # 2
"""Bad value for the register"""
ERR_LTC_REG_READ_ONLY: LTCRegisterError.ValueType  # 3
"""Register is read-only"""
ERR_LTC_ACCESS_FAILED: LTCRegisterError.ValueType  # 4
"""LTC7871 access failed/unavailable"""
global___LTCRegisterError = LTCRegisterError

@typing.final
class PingNodeRequest(google.protobuf.message.Message):
    """****************************************************************************
    Ping Node Service
    ****************************************************************************
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HEADER_FIELD_NUMBER: builtins.int
    NODE_ID_FIELD_NUMBER: builtins.int
    node_id: builtins.int
    @property
    def header(self) -> mbed_rpc_pb2.Header: ...
    def __init__(
        self,
        *,
        header: mbed_rpc_pb2.Header | None = ...,
        node_id: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["header", b"header", "node_id", b"node_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["header", b"header", "node_id", b"node_id"]) -> None: ...

global___PingNodeRequest = PingNodeRequest

@typing.final
class PingNodeResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HEADER_FIELD_NUMBER: builtins.int
    @property
    def header(self) -> mbed_rpc_pb2.Header: ...
    def __init__(
        self,
        *,
        header: mbed_rpc_pb2.Header | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["header", b"header"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["header", b"header"]) -> None: ...

global___PingNodeResponse = PingNodeResponse

@typing.final
class GetIdRequest(google.protobuf.message.Message):
    """****************************************************************************
    Identity Service
    ****************************************************************************

    This is a broadcasted message to all nodes in the network to respond with their unique identifier.
    This allows a master controller to figure out who is in the network for later communication.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HEADER_FIELD_NUMBER: builtins.int
    @property
    def header(self) -> mbed_rpc_pb2.Header: ...
    def __init__(
        self,
        *,
        header: mbed_rpc_pb2.Header | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["header", b"header"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["header", b"header"]) -> None: ...

global___GetIdRequest = GetIdRequest

@typing.final
class GetIdResponse(google.protobuf.message.Message):
    """Response to the GetIdRequest message. This contains the unique identifier of the node and a software
    version to help with compatibility decisions.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HEADER_FIELD_NUMBER: builtins.int
    UNIQUE_ID_FIELD_NUMBER: builtins.int
    VER_MAJOR_FIELD_NUMBER: builtins.int
    VER_MINOR_FIELD_NUMBER: builtins.int
    VER_PATCH_FIELD_NUMBER: builtins.int
    unique_id: builtins.int
    ver_major: builtins.int
    ver_minor: builtins.int
    ver_patch: builtins.int
    @property
    def header(self) -> mbed_rpc_pb2.Header: ...
    def __init__(
        self,
        *,
        header: mbed_rpc_pb2.Header | None = ...,
        unique_id: builtins.int | None = ...,
        ver_major: builtins.int | None = ...,
        ver_minor: builtins.int | None = ...,
        ver_patch: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["header", b"header", "unique_id", b"unique_id", "ver_major", b"ver_major", "ver_minor", b"ver_minor", "ver_patch", b"ver_patch"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["header", b"header", "unique_id", b"unique_id", "ver_major", b"ver_major", "ver_minor", b"ver_minor", "ver_patch", b"ver_patch"]) -> None: ...

global___GetIdResponse = GetIdResponse

@typing.final
class ManagerRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HEADER_FIELD_NUMBER: builtins.int
    NODE_ID_FIELD_NUMBER: builtins.int
    COMMAND_FIELD_NUMBER: builtins.int
    node_id: builtins.int
    command: global___ManagerCommand.ValueType
    @property
    def header(self) -> mbed_rpc_pb2.Header: ...
    def __init__(
        self,
        *,
        header: mbed_rpc_pb2.Header | None = ...,
        node_id: builtins.int | None = ...,
        command: global___ManagerCommand.ValueType | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["command", b"command", "header", b"header", "node_id", b"node_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["command", b"command", "header", b"header", "node_id", b"node_id"]) -> None: ...

global___ManagerRequest = ManagerRequest

@typing.final
class ManagerResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HEADER_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    status: global___ManagerError.ValueType
    message: builtins.str
    @property
    def header(self) -> mbed_rpc_pb2.Header: ...
    def __init__(
        self,
        *,
        header: mbed_rpc_pb2.Header | None = ...,
        status: global___ManagerError.ValueType | None = ...,
        message: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["header", b"header", "message", b"message", "status", b"status"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["header", b"header", "message", b"message", "status", b"status"]) -> None: ...

global___ManagerResponse = ManagerResponse

@typing.final
class SetpointRequest(google.protobuf.message.Message):
    """Control a node's operational setpoints for parameters like voltage, current, etc."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HEADER_FIELD_NUMBER: builtins.int
    NODE_ID_FIELD_NUMBER: builtins.int
    FIELD_FIELD_NUMBER: builtins.int
    UINT32_TYPE_FIELD_NUMBER: builtins.int
    FLOAT_TYPE_FIELD_NUMBER: builtins.int
    node_id: builtins.int
    field: global___SetpointField.ValueType
    """Which field to set"""
    uint32_type: builtins.int
    float_type: builtins.float
    @property
    def header(self) -> mbed_rpc_pb2.Header: ...
    def __init__(
        self,
        *,
        header: mbed_rpc_pb2.Header | None = ...,
        node_id: builtins.int | None = ...,
        field: global___SetpointField.ValueType | None = ...,
        uint32_type: builtins.int | None = ...,
        float_type: builtins.float | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["field", b"field", "float_type", b"float_type", "header", b"header", "node_id", b"node_id", "uint32_type", b"uint32_type", "value_oneof", b"value_oneof"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["field", b"field", "float_type", b"float_type", "header", b"header", "node_id", b"node_id", "uint32_type", b"uint32_type", "value_oneof", b"value_oneof"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["value_oneof", b"value_oneof"]) -> typing.Literal["uint32_type", "float_type"] | None: ...

global___SetpointRequest = SetpointRequest

@typing.final
class SetpointResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HEADER_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    status: global___SetpointError.ValueType
    message: builtins.str
    @property
    def header(self) -> mbed_rpc_pb2.Header: ...
    def __init__(
        self,
        *,
        header: mbed_rpc_pb2.Header | None = ...,
        status: global___SetpointError.ValueType | None = ...,
        message: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["header", b"header", "message", b"message", "status", b"status"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["header", b"header", "message", b"message", "status", b"status"]) -> None: ...

global___SetpointResponse = SetpointResponse

@typing.final
class SensorRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HEADER_FIELD_NUMBER: builtins.int
    NODE_ID_FIELD_NUMBER: builtins.int
    SENSOR_FIELD_NUMBER: builtins.int
    node_id: builtins.int
    sensor: global___SensorType.ValueType
    @property
    def header(self) -> mbed_rpc_pb2.Header: ...
    def __init__(
        self,
        *,
        header: mbed_rpc_pb2.Header | None = ...,
        node_id: builtins.int | None = ...,
        sensor: global___SensorType.ValueType | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["header", b"header", "node_id", b"node_id", "sensor", b"sensor"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["header", b"header", "node_id", b"node_id", "sensor", b"sensor"]) -> None: ...

global___SensorRequest = SensorRequest

@typing.final
class SensorResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HEADER_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    status: global___SensorError.ValueType
    value: builtins.float
    @property
    def header(self) -> mbed_rpc_pb2.Header: ...
    def __init__(
        self,
        *,
        header: mbed_rpc_pb2.Header | None = ...,
        status: global___SensorError.ValueType | None = ...,
        value: builtins.float | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["header", b"header", "status", b"status", "value", b"value"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["header", b"header", "status", b"status", "value", b"value"]) -> None: ...

global___SensorResponse = SensorResponse

@typing.final
class LTCRegisterSetRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HEADER_FIELD_NUMBER: builtins.int
    NODE_ID_FIELD_NUMBER: builtins.int
    REG_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    node_id: builtins.int
    reg: builtins.int
    value: builtins.int
    @property
    def header(self) -> mbed_rpc_pb2.Header: ...
    def __init__(
        self,
        *,
        header: mbed_rpc_pb2.Header | None = ...,
        node_id: builtins.int | None = ...,
        reg: builtins.int | None = ...,
        value: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["header", b"header", "node_id", b"node_id", "reg", b"reg", "value", b"value"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["header", b"header", "node_id", b"node_id", "reg", b"reg", "value", b"value"]) -> None: ...

global___LTCRegisterSetRequest = LTCRegisterSetRequest

@typing.final
class LTCRegisterSetResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HEADER_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    status: global___LTCRegisterError.ValueType
    @property
    def header(self) -> mbed_rpc_pb2.Header: ...
    def __init__(
        self,
        *,
        header: mbed_rpc_pb2.Header | None = ...,
        status: global___LTCRegisterError.ValueType | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["header", b"header", "status", b"status"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["header", b"header", "status", b"status"]) -> None: ...

global___LTCRegisterSetResponse = LTCRegisterSetResponse

@typing.final
class LTCRegisterGetRequest(google.protobuf.message.Message):
    """****************************************************************************
    LTC Register Get Service
    ****************************************************************************
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HEADER_FIELD_NUMBER: builtins.int
    NODE_ID_FIELD_NUMBER: builtins.int
    REG_FIELD_NUMBER: builtins.int
    node_id: builtins.int
    reg: builtins.int
    @property
    def header(self) -> mbed_rpc_pb2.Header: ...
    def __init__(
        self,
        *,
        header: mbed_rpc_pb2.Header | None = ...,
        node_id: builtins.int | None = ...,
        reg: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["header", b"header", "node_id", b"node_id", "reg", b"reg"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["header", b"header", "node_id", b"node_id", "reg", b"reg"]) -> None: ...

global___LTCRegisterGetRequest = LTCRegisterGetRequest

@typing.final
class LTCRegisterGetResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HEADER_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    status: global___LTCRegisterError.ValueType
    value: builtins.int
    @property
    def header(self) -> mbed_rpc_pb2.Header: ...
    def __init__(
        self,
        *,
        header: mbed_rpc_pb2.Header | None = ...,
        status: global___LTCRegisterError.ValueType | None = ...,
        value: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["header", b"header", "status", b"status", "value", b"value"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["header", b"header", "status", b"status", "value", b"value"]) -> None: ...

global___LTCRegisterGetResponse = LTCRegisterGetResponse
