"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import mbed_rpc_pb2
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class GetIdRequest(google.protobuf.message.Message):
    """This is a broadcasted message to all nodes in the network to respond with their unique identifier.
    This allows a master controller to figure out who is in the network for later communication.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HEADER_FIELD_NUMBER: builtins.int
    @property
    def header(self) -> mbed_rpc_pb2.Header: ...
    def __init__(
        self,
        *,
        header: mbed_rpc_pb2.Header | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["header", b"header"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["header", b"header"]) -> None: ...

global___GetIdRequest = GetIdRequest

@typing.final
class GetIdResponse(google.protobuf.message.Message):
    """Response to the GetIdRequest message. This contains the unique identifier of the node and a software
    version to help with compatibility decisions.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HEADER_FIELD_NUMBER: builtins.int
    UNIQUE_ID_FIELD_NUMBER: builtins.int
    VER_MAJOR_FIELD_NUMBER: builtins.int
    VER_MINOR_FIELD_NUMBER: builtins.int
    VER_PATCH_FIELD_NUMBER: builtins.int
    unique_id: builtins.int
    ver_major: builtins.int
    ver_minor: builtins.int
    ver_patch: builtins.int
    @property
    def header(self) -> mbed_rpc_pb2.Header: ...
    def __init__(
        self,
        *,
        header: mbed_rpc_pb2.Header | None = ...,
        unique_id: builtins.int | None = ...,
        ver_major: builtins.int | None = ...,
        ver_minor: builtins.int | None = ...,
        ver_patch: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["header", b"header", "unique_id", b"unique_id", "ver_major", b"ver_major", "ver_minor", b"ver_minor", "ver_patch", b"ver_patch"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["header", b"header", "unique_id", b"unique_id", "ver_major", b"ver_major", "ver_minor", b"ver_minor", "ver_patch", b"ver_patch"]) -> None: ...

global___GetIdResponse = GetIdResponse
