# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ichnaea.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'ichnaea.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import nanopb_pb2 as nanopb__pb2
import mbed_rpc_pb2 as mbed__rpc__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\richnaea.proto\x12\x07ichnaea\x1a\x0cnanopb.proto\x1a\x0embed_rpc.proto\"0\n\x0cGetIdRequest\x12 \n\x06header\x18\x01 \x02(\x0b\x32\x10.mbed.rpc.Header\"\x92\x01\n\rGetIdResponse\x12 \n\x06header\x18\x01 \x02(\x0b\x32\x10.mbed.rpc.Header\x12\x11\n\tunique_id\x18\x02 \x02(\r\x12\x18\n\tver_major\x18\x03 \x02(\rB\x05\x92?\x02\x38\x08\x12\x18\n\tver_minor\x18\x04 \x02(\rB\x05\x92?\x02\x38\x08\x12\x18\n\tver_patch\x18\x05 \x02(\rB\x05\x92?\x02\x38\x08')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ichnaea_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETIDRESPONSE'].fields_by_name['ver_major']._loaded_options = None
  _globals['_GETIDRESPONSE'].fields_by_name['ver_major']._serialized_options = b'\222?\0028\010'
  _globals['_GETIDRESPONSE'].fields_by_name['ver_minor']._loaded_options = None
  _globals['_GETIDRESPONSE'].fields_by_name['ver_minor']._serialized_options = b'\222?\0028\010'
  _globals['_GETIDRESPONSE'].fields_by_name['ver_patch']._loaded_options = None
  _globals['_GETIDRESPONSE'].fields_by_name['ver_patch']._serialized_options = b'\222?\0028\010'
  _globals['_GETIDREQUEST']._serialized_start=56
  _globals['_GETIDREQUEST']._serialized_end=104
  _globals['_GETIDRESPONSE']._serialized_start=107
  _globals['_GETIDRESPONSE']._serialized_end=253
# @@protoc_insertion_point(module_scope)
