/*
 * This file has been auto-generated by CppUMockGen v0.6.
 *
 * Contents will NOT be preserved if it is regenerated!!!
 *
 * Generation options: -s c++20
 */

#include "../../src/system/panic_handlers.hpp"

#include <CppUTestExt/MockSupport.h>

bool Panic::Handlers::DefaultHandler(const Panic::ErrorCode & code)
{
    return mock().actualCall("Panic::Handlers::DefaultHandler").withConstPointerParameter("code", &code).returnBoolValue();
}

bool Panic::Handlers::NoopHandler(const Panic::ErrorCode & code)
{
    return mock().actualCall("Panic::Handlers::NoopHandler").withConstPointerParameter("code", &code).returnBoolValue();
}

bool Panic::Handlers::FailToReadBoardVersion(const Panic::ErrorCode & code)
{
    return mock().actualCall("Panic::Handlers::FailToReadBoardVersion").withConstPointerParameter("code", &code).returnBoolValue();
}

