/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8 */

#ifndef PB_ICHNAEA_ICHNAEA_PDI_PB_H_INCLUDED
#define PB_ICHNAEA_ICHNAEA_PDI_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* KEY_BOOT_COUNT */
typedef struct _ichnaea_PDI_BootCount {
    uint32_t boot_count;
} ichnaea_PDI_BootCount;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define ichnaea_PDI_BootCount_init_default       {0}
#define ichnaea_PDI_BootCount_init_zero          {0}

/* Field tags (for use in manual encoding/decoding) */
#define ichnaea_PDI_BootCount_boot_count_tag     1

/* Struct field encoding specification for nanopb */
#define ichnaea_PDI_BootCount_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   boot_count,        1)
#define ichnaea_PDI_BootCount_CALLBACK NULL
#define ichnaea_PDI_BootCount_DEFAULT NULL

extern const pb_msgdesc_t ichnaea_PDI_BootCount_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define ichnaea_PDI_BootCount_fields &ichnaea_PDI_BootCount_msg

/* Maximum encoded size of messages (where known) */
#define ICHNAEA_ICHNAEA_PDI_PB_H_MAX_SIZE        ichnaea_PDI_BootCount_size
#define ichnaea_PDI_BootCount_size               6

#ifdef __cplusplus
} /* extern "C" */
#endif

#ifdef __cplusplus
/* Message descriptors for nanopb */
namespace nanopb {
template <>
struct MessageDescriptor<ichnaea_PDI_BootCount> {
    static PB_INLINE_CONSTEXPR const pb_size_t fields_array_length = 1;
    static inline const pb_msgdesc_t* fields() {
        return &ichnaea_PDI_BootCount_msg;
    }
};
}  // namespace nanopb

#endif  /* __cplusplus */


#endif
