/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 */

#include "ichnaea_pdi.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(ichnaea_PDI_BootCount, ichnaea_PDI_BootCount, AUTO)


PB_BIND(ichnaea_PDI_SerialNumber, ichnaea_PDI_SerialNumber, AUTO)


PB_BIND(ichnaea_PDI_ManufactureDate, ichnaea_PDI_ManufactureDate, AUTO)


PB_BIND(ichnaea_PDI_CalibrationDate, ichnaea_PDI_CalibrationDate, AUTO)


PB_BIND(ichnaea_PDI_FloatConfiguration, ichnaea_PDI_FloatConfiguration, AUTO)


PB_BIND(ichnaea_PDI_Uint32Configuration, ichnaea_PDI_Uint32Configuration, AUTO)


PB_BIND(ichnaea_PDI_BooleanConfiguration, ichnaea_PDI_BooleanConfiguration, AUTO)


PB_BIND(ichnaea_PDI_IIRFilterConfig, ichnaea_PDI_IIRFilterConfig, AUTO)


PB_BIND(ichnaea_PDI_BasicCalibration, ichnaea_PDI_BasicCalibration, AUTO)





